# Generated by Django 4.1.3 on 2022-11-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daraz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='TestProduct',
        ),
    ]
